spin_manifest_version = "1"
authors = ["Maximiliano Capodacqua <kapomaxi1@gmail.com>"]
description = "Receives a message from a redis instance"
name = "barbenheimer-redis"
trigger = { type = "redis", address = "redis://localhost:6379" }
version = "0.1.0"

[[component]]
id = "counter"
source = "counter/target/wasm32-wasi/release/counter.wasm"
allowed_http_hosts = []
sqlite_databases = ["default"]
[component.trigger]
channel = "vote"
[component.build]
workdir = "counter"
command = "make"
# command = "cargo build --target wasm32-wasi --release"
