spin_manifest_version = "1"
authors = ["Maximiliano Capodacqua <kapomaxi1@gmail.com>"]
description = ""
name = "barbenheimer"
trigger = { type = "http", base = "/" }
version = "0.1.0"


[[component]]
id = "publish-vote"
source = "wasm/publish-vote.wasm"
environment = { REDIS_ADDRESS = "redis://127.0.0.1:6379", REDIS_CHANNEL = "vote" }
[component.trigger]
route = "/vote"
[component.build]
workdir= "publish-vote"
command = "tinygo build -target=wasi -gc=leaking -no-debug -o ../wasm/publish-vote.wasm main.go"

[[component]]
id = "scoring"
source = "wasm/scoring.wasm"
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/scoring"
[component.build]
workdir= "scoring"
command = "npm run build"
