spin_manifest_version = "1"
authors = ["Maximiliano Capodacqua <kapomaxi1@gmail.com>"]
description = ""
name = "barbenheimer"
trigger = { type = "http", base = "/" }
version = "0.1.0"


[[component]]
id = "publish-vote"
source = "wasm/publish-vote.wasm"
environment = { REDIS_ADDRESS = "redis://127.0.0.1:6379", REDIS_CHANNEL = "vote" }
[component.trigger]
route = "/vote"
[component.build]
workdir= "publish-vote"
watch=["*.go", "go.mod", "go.sum"]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o ../wasm/publish-vote.wasm main.go"

[[component]]
id = "scoring"
source = "wasm/scoring.wasm"
sqlite_databases = ["default"]
exclude_files = ["**/node_modules"]
[component.trigger]
route = "/scoring"
[component.build]
workdir= "scoring"
watch=["src/**/*.ts", "*.js", "*.json"]
command = "npm run build"

[[component]]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
id = "site"
files = [ { source = "site/build/", destination = "/" } ]
[component.trigger]
route = "/..."
